export const enum ActionType {
  UPDATE_MARKET_DATA_REQUEST,
  UPDATE_MARKET_DATA_SUCCESS,
  UPDATE_MARKET_DATA_FAILURE,

  SET_SHOW_FILTERS,

  ADD_FAVORITE_MARKET,
  REMOVE_FAVORITE_MARKET,
  SET_FAVORITE_MARKETS
}
